[project]
name = "hermitlm"
version = "0.1.0"
description = "A compact conversational language model with an in-browser chat website"
authors = [{name="darshi1337"}]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "torch",
    "tokenizers",
    "python-dotenv",
    "requests",
    "fastapi",
    "uvicorn",
    "pydantic",
    "ddgs",
]

[project.scripts]
hermitlm = "hermitlm.__main__:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["hermitlm*"]

[tool.setuptools.package-data]
hermitlm = ["static/*.html"]
